- src/string.rs
While actually running the test suites just to see what happens I noticed a panic that occurs due to the `copy_from_slice` function asserting that both slices are of the same length.
> Fix possible string slice length panic

- src/bin/luster.rs
Commit has the wrong c word technology on it because I am daft.  This is a minor patch to pull crate information at compile time using clap.  Should have been like this to begin with.  I'd been meaning to do this for a bit.
> Use clap better

- gc-arena/src/gc.rs
- src/bin/compiler.rs
- src/bin/luster.rs
- src/closure.rs
First of all, thanks for the amazing project! I learned a lot from it. :)
This PR added a new command line flag `--dump`(`-d`). When provided, luster will print the parsed bytecode without actually running the code. I find it pretty useful for understanding the internal. It might also be helpful for others.
For now, I just dump the `FunctionProto` with `Debug` trait with minimal formatting. It's definitely note a good textual representation of luster's bytecode. However, it's fine for learning purpose IMO.
Example:
```lua
-- test.lua
local x = 1
function foo(y)
return x + y
end
print(foo(2))
```
```
$ luster --dump test.lua
=============
FunctionProto(0x7ffee596b9d0)
=============
fixed_params: 0, has_varargs: true, stack_size: 4
constants:
0: Integer(1)
1: String(Short8(3, Gc { ptr: …
```
> add `luster --dump` flag to print the parsed bytecode

- examples/compiler.rs
I found the compiler example useful for experimenting with.
This just adds a tiny update to indent nested prototypes so that it's easier to see the tree structure.
> feat: make nesting more apparent in compiler example.

- src/lib.rs
tbh, it feels like this should be the default for re-exported things. Rust doc search is pretty awful when they aren't inlined, since you end up seeing two items in the results, one of which is the re-export which requires yet another click to get to the page you're actually looking for.
Alternatively, the target of the re-export could be made non-public, which would have the same effect as far as docs go.
> use `#[doc(inline)]` for re-exports

- src/stdlib/math.rs
- tests/scripts/math.lua
PUC-Lua has different behavior if `math.random(0)` is executed, as 0 is not in [1, n) for any n.
This changes the code to match that behavior.
Also fixes the crash from `math.random(v)` where `v` < 0 and makes it a Lua error.
I poked the function until it cried, so I included a fix for `math.random([n, ]math.maxinteger)`...
> fix: math.random

- src/stdlib/math.rs
- tests/scripts/math.lua
Matches the interface for piccolo's `math.log` function to that of PUC-Lua.
We take advantage of Rust's optimized (?) functions when the requested base matches one of the routines, but we can now handle any base directly.
> make math.log match PUC-Lua

- src/stdlib/math.rs
- tests/scripts/math.lua
Clean history for `math.randomseed`.
Supersedes #49
> math.randomseed impl

- src/stdlib/math.rs
Fix the seed code so that instead of being fixed to [u8; 32], the `SeedableRng::Seed` type is allowed to be `[u32; N]` (through the use of `std::array::from_fn`), and the seed is simply the low and high bytes repeated in order, ad infinitum.
> fix: allow seed to be any size

- src/meta_ops.rs
realized this should be the case from Lua 5.4 manual:
>Like with indexing, the metavalue for this event can be either a function, a table, or any value with an __newindex metavalue. If it is a function, it is called with table, key, and value as arguments. Otherwise, Lua repeats the indexing assignment over this metavalue with the same key and value. This assignment is regular, not raw, and therefore can trigger another __newindex metavalue.
> Mirror `__index` change to `__newindex`

- COMPATIBILITY.md
- src/stdlib/string.rs
- tests/scripts/string.lua
I wanted to sub my strings, so I made a quick implementation
> implement string.sub

- src/stdlib/base.rs
- tests/scripts/tonumber.lua
I caught too many Zs...
luckily the manual had something to say about this:
> Unless stated otherwise, any overflow when manipulating integer values wrap around, according to the usual rules of two-complement arithmetic. (In other words, the actual result is the unique representable integer that is equal modulo 2n to the mathematical result, where n is the number of bits of the integer type.)
so here we are
**UPDATE**
> I would be fine with just whatever saturating_add does, even if it doesn't match
> I don't want to mimic weird overflow behavior
kyren has spoken.
**UPDATE UPDATE**
too many Zs spoiled the broth.
> fix: be correct so we don't burn from Zs

- src/meta_ops.rs
- src/raw_ops.rs
- src/stdlib/base.rs
- src/thread/mod.rs
- src/thread/vm.rs
- tests/scripts/metaop_add.lua
- tests/scripts/metaops.lua
- tests/tail_call_stack_panic.rs
Adds support for the `__add`, `__sub`, `__mul`, and `__div` metamethods.
In addition, this PR adds slightly more context to errors when no metamethod was found; errors include the attempted operation and the relevant types.  (The formatting is done through `thiserror` and the standard formatting machinery.)
The error handling and metamethod changes are in separate commits, for ease of review / cherry-picking.
I implemented this before I saw #57, so feel free to close this if that gets merged. 
I'm mainly creating this PR in case my implementation ends up being helpful; even if this impl isn't used, the test cases are a bit more extensive and could be merged into #57.
> Add support for basic arithmetic metamethods, improve operator error messages

- src/conversion.rs
- src/error.rs
- src/meta_ops.rs
- src/stdlib/base.rs
- src/stdlib/io.rs
- src/stdlib/string.rs
- src/value.rs
- util/src/serde/de.rs
This makes `Value` no longer directly implement `fmt::Display`, so it no longer has a `to_string` method.  This is probably a good thing, as calling `to_string` would silently corrupt non-utf8 data.
Method changes:
- rename `Value::display` to `Value::write`
- add `Value::display(self) -> impl Display`
- add `Value::into_string(self, ctx) -> Option<String<'gc>>`
- add `Value::is_implicit_string(self) -> bool`
Adds a `FromValue` impl for `string::String<'gc>`
This significantly reduces the boilerplate for stdlib methods that deal with strings.
> Unify string conversion logic, remove Value::to_string footgun

- tests/scripts-wishlist/globals.lua
- tests/scripts.rs
Simple patch to add support for non-required tests, to make it easier to keep track of lower-priority compatibility bugs.
> Add wishlist (non-required) tests

- util/src/serde/de.rs
When deserializing serde values (that could be anything), if a string only consists of valid UTF-8, attempt to go down the string path.
> Valid UTF-8 when deserializing on serde

- src/fuel.rs
- src/stdlib/table.rs
- src/table/mod.rs
- src/table/raw.rs
- src/thread/thread.rs
- tests/scripts/table.lua
- Implement `table.insert` and `table.remove`, supporting metamethods
- For plain tables (no index/newindex/len metamethods), optimize inserts and removes that work entirely within the array portion of the table; this is the normal use-case of `table.insert` and `table.remove`, so it should be worth the minor added complexity.
This now includes a reasonable set of tests, though the edge cases of the optimized case may be difficult to trigger explicitly.
> Implement `table.insert` and `table.remove`

- COMPATIBILITY.md
- src/async_callback.rs
- src/meta_ops.rs
- src/stack.rs
- src/stdlib/table.rs
- src/stdlib/table/move.lua
- src/stdlib/table/sort.lua
- src/string.rs
- src/thread/mod.rs
- src/thread/thread.rs
- src/thread/vm.rs
- tests/scripts/concat.lua
- tests/scripts/metaops.lua
- tests/scripts/sort.lua
- tests/scripts/table_concat.lua
- tests/scripts/table_move.lua
At some point it would be good to have `table.move` and `table.sort` implemented in Rust, but for now a Lua implementation works.
This PR also implements the `__concat` metamethod, and uses it to implement `table.concat`; unlike PRLua's implementation, this version supports tables with the `__concat` metamethod.
For example, `table.concat({ a, b, c }, sep)` is equivalent to `a .. sep .. b .. sep .. c`, and respects the right-associativity of the `..` operator.
Semantics questions on `table.concat`:
- Should `table.concat({ x }) == x`, regardless of type?  It currently does, as it never tries to call the `__concat` metaoperator.
- Is the complexity of this worth it over only supporting string/integers in `table.concat`?
> Implement `__concat`, `table.concat`, and add Lua polyfills for `table.sort` and `table.move`

- src/meta_ops.rs
The `estimate_concatenated_len` calculates a ilog10 if the value is integer. The method panics for non-positive values:
https://doc.rust-lang.org/std/primitive.i64.html#method.ilog10
> Fix estimate_concatenated_len for non-positive integers.

- .circleci/config.yml
Fixes CI: `error: package `home v0.5.11` cannot be built because it requires rustc 1.81 or newer, while the currently active rustc version is 1.77.2`
> Rust version bump in the CI

- COMPATIBILITY.md
- src/stdlib/string.rs
- tests/scripts/string.lua
Add `string.byte` and `string.char` to the standard library.
> Implement `string.byte` and `string.char`

- src/compiler/string_utils.rs
- src/stdlib/math.rs
This adds an implementation of `ldexp` to more closely match PUC-Rio Lua's hexfloat parsing, which allows us to parse subnormal hexfloats (and is significantly faster than `exp2`).
This also reorganizes the math module to make it easier to selectively disable parts, which will be necessary for supporting `#![no_std]` cleanly, as many float methods only exist in `std`.
> Refactor math library for #![no_std] support, support parsing subnormal hexfloats

- examples/compiler.rs
- examples/execute.rs
- examples/interpreter.rs
- src/closure.rs
- src/compiler/lexer.rs
- src/compiler/parser.rs
- tests/scripts.rs
This makes the lexer (and in turn the parser) use byte slices rather than a generic `impl Read` for the program source.  This has two main benefits:
- `std::io::Read` is unsupported on `#![no_std]`, so we'll need to switch away from it eventually
- This should reduce compilation time and code size for crates that depend on `piccolo`.  Generic methods are instantiated in the calling crate, so currently each crate that loads Lua code compiles its own copy of the parser (and compiler, for reasons) for each type that `impl Read` is substituted for.  See #94 for more details, but this fixes the issue and supersedes #​94.
> Use byte slices instead of impl Read in lexer and parser

- src/stdlib/table.rs
- tests/scripts/overflow.lua
This fixes a number of integer overflows in the length handling of `table.insert` and `table.remove`; piccolo now handles these differently from PRLua by explicitly throwing errors if the lengths are too large, rather than wrapping them and having subsequent buggy behavior.
> Fix integer overflows in `table.insert` and `table.remove`

- src/stack.rs
- src/string.rs
- src/thread/thread.rs
Minor lint fixes so that our Miri runs in CI don't fail.  (As a side note, it would probably be good to pin the nightly version used for Miri in CI, to reduce unscheduled breakage?)
> Fix new lints for nightly CI

- src/thread/thread.rs
- src/thread/vm.rs
- tests/scripts/pcall_concat_err.lua
**Edit**: This is a more major issue, and the fallback concat metamethod impl can corrupt the Lua stack even when it shouldn't error.  I've changed this PR to fully remove the faulty optimization, since it wasn't worth the complexity and debugging effort.
Currently, if the concat operator has a type error while running in a `pcall` context, it can corrupt the stack above the pcall.
A minimal reproduction is this:
```lua
local a, b, c
pcall(function() print(""..nil) end)
```
Which results in the following panic:
```
thread 'main' panicked at src/stack.rs:27:9:
assertion failed: values.len() >= bottom
stack backtrace:
...
2: core::panicking::panic
at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:145:5
3: piccolo::stack::Stack::new
at ./src/stack.rs:27:9
4: …
```
> Remove faulty concat optimization
